### ISSUE TITLE
Users (and guest users) can't write unless they are admin (root).

### ISSUE THREAD

**Issue by jtagcat** [Erriez/docker-samba#11] opened 2021-12-30 20:58 UTC
At least when host's all perms are nobody:nobody, chown not allowed.

This was an issue on upstream, unsure if on the fork as well.

**Comment by Erriez** [comment] 2021-12-31 20:07
Thanks for creating an issue. I was not able to reproduce this with tagged version `1.0.0` on Linux:

```bash
# Create share as normal user:
mkdir /tmp/share2
```

**docker-compose.yml**:
Create share with browsable, read/write, guest access permission:
```yaml
volumes:
      - /tmp/share1:/mnt:z
      - /tmp/share2:/share2:z
    # -s <name>; <path> [; browse; readonly; guest; users; admins; writelist; comment]
    command: '-s "Private share2;/share2;yes;no;yes" -p'
```

Files are read/writable via the Samba share. Can you reproduce this with `1.0.0`?

**Comment by Erriez** [comment] 2022-01-01 10:54
Update: Option `-p   Set ownership and permissions on the shares` is intended to correct permissions on shared directories. Without this option, the directory created as normal user is read-only via Windows Explorer:

```
# Read only in Windows Explorer:
drwxrwxr-x  4 user group    4096 jan  1 11:34 share2/

# Fixed permission with `-p` option and read-writable in Windows Explorer:
drwxrwxr-x  4 systemd-network systemd-journal 4096 jan  1 11:34 share2/
```

Closing issue. Don't hesitate to add comments on this topic.

**Closed by Erriez** 2022-01-01 10:54 UTC
Labels: question

**Comment by jtagcat** [comment] 2022-01-01 17:16
`-p` is simply not possible.  
On the host:
```
$ ls -la
.rw-rw-r-- 0 nobody  1 Jan 17:10 a
$ chown 1000:1000 a
chown: changing ownership of 'a': Invalid argument
```

The docker host mounts an NFS mount. The server uses the following options: `rw=foo,sec=sys,crossmnt,no_subtree_check,all_squash,anonuid=1003,anongid=1003`

Running chown in a container returns permission denied, as expected. The permissions can't be changed. It's set in stone.

> Can you reproduce this with 1.0.0?

Yes. It is likely due to all files being owned by nobody:nobody (65534). Both inside and outside the container.

**Comment by Erriez** [comment] 2022-01-01 21:18
> $ chown 1000:1000 a

Is it possible to change ownership with sudo?

On my system nobody group does not exists, but can be changed on a normal directory with `$ sudo chown nobody:nogroup a`. I'm not sure how this works for NFS.

Any suggestion how you want to proceed with this?

**Comment by jtagcat** [comment] 2022-01-01 21:40
> Is it possible to change ownership with sudo?

No, the filesystem does not support it. The ownership is just always `nobody:nobody`.

> Any suggestion how you want to proceed with this?

I threw samba in the trash and moved on, I don't personally care anymore.
